<template>
	<v-card>
		<v-card-title>
		<v-text-field
			v-model="search"
			append-icon="mdi-magnify"
			label="Search"
			single-line
			hide-details
		></v-text-field>
		</v-card-title>
		<v-data-table
		:headers="tableHeader"
		:items="tableData"
		:search="search"
		></v-data-table>
  	</v-card>
</template>
<script>
export default {
	props:{
		tableHeader:Array,
		tableData:Array,
	},
	data(){
		return{
			search:''
		}
	},
	mounted(){
		console.log('tableHeader= ',this.tableHeader)
	}
}
</script>